language: node_js
node_js:
  - 8
cache:	
  directories:	
    - node_modules
addons:	
  artifacts: true
jobs:
  include:
    - stage: "Install"
      script: npm ci
    - stage: "Test & Coverage"
      script: npm test -- -u --collectCoverage=true && npm run coveralls